const products = [
  {
    id: "1",
    text: "Sony WH-1000XM4",
    description: ["It's a good pair of headphones", "Second point"],
    price: 215.99,
    image:
      "https://www.sony.co.uk/image/5d02da5df552836db894cead8a68f5f3?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF",
  },
  {
    id: "2",
    text: "Anker Soundcore Liberty Air 2",
    description: ["It's a good pair of headphones", "Second point"],
    price: 99.99,
    image:
      "https://m.media-amazon.com/images/I/61mlqxZ6dvL._AC_UF1000,1000_QL80_DpWeblab_.jpg",
  },
  {
    id: "3",
    text: "Logitech MX Master 3",
    description: ["It's a good pair of headphones", "Second point"],
    price: 99.99,
    image:
      "https://scale.coolshop-cdn.com/product-media.coolshop-cdn.com/23D5RT/c9a6fd63030b4db088817dce70f4ba28.png/f/logitech-mx-master-3s-for-mac-performance-wireless-mouse-space-grey.png",
  },
  {
    id: "4",
    text: "Amazon Echo Dot (4th Gen)",
    description: ["It's a good pair of headphones", "Second point"],
    price: 49.99,
    image: "https://example.com/images/echo_dot.jpg",
  },
  {
    id: "5",
    text: "Roku Streaming Stick+",
    description: ["It's a good pair of headphones", "Second point"],
    price: 49.99,
    image: "https://example.com/images/roku_stick.jpg",
  },
  {
    id: "6",
    text: "TP-Link Kasa Smart Plug",
    description: ["It's a good pair of headphones", "Second point"],
    price: 19.99,
    image: "https://example.com/images/tp_link_kasa.jpg",
  },
  {
    id: "7",
    text: "SanDisk 128GB Ultra Dual Drive",
    description: ["It's a good pair of headphones", "Second point"],
    price: 24.99,
    image: "https://example.com/images/sandisk_dual_drive.jpg",
  },
  {
    id: "8",
    text: "Xiaomi Mi Band 6",
    description: ["It's a good pair of headphones", "Second point"],
    price: 44.99,
    image: "https://example.com/images/mi_band_6.jpg",
  },
  {
    id: "9",
    text: "Amazon Fire TV Stick",
    description: ["It's a good pair of headphones", "Second point"],
    price: 39.99,
    image: "https://example.com/images/fire_tv_stick.jpg",
  },
  {
    id: "10",
    text: "Google Chromecast",
    description: ["It's a good pair of headphones", "Second point"],
    price: 29.99,
    image: "https://example.com/images/chromecast.jpg",
  },
  {
    id: "11",
    text: "JBL Go 3 Portable Speaker",
    description: ["It's a good pair of headphones", "Second point"],
    price: 39.99,
    image: "https://example.com/images/jbl_go_3.jpg",
  },
  {
    id: "12",
    text: "RAVPower Portable Charger 10000mAh",
    description: ["It's a good pair of headphones", "Second point"],
    price: 29.99,
    image: "https://example.com/images/ravpower_charger.jpg",
  },
  {
    id: "13",
    text: "AUKEY USB C Charger 18W",
    description: ["It's a good pair of headphones", "Second point"],
    price: 19.99,
    image: "https://example.com/images/aukey_charger.jpg",
  },
  {
    id: "14",
    text: "Kasa Smart Light Bulb",
    description: ["It's a good pair of headphones", "Second point"],
    price: 14.99,
    image: "https://example.com/images/kasa_smart_bulb.jpg",
  },
  {
    id: "15",
    text: "Tile Mate (2020)",
    description: ["It's a good pair of headphones", "Second point"],
    price: 24.99,
    image: "https://example.com/images/tile_mate.jpg",
  },
  {
    id: "16",
    text: "Sony MDRZX110NC Noise Cancelling Headphones",
    description: ["It's a good pair of headphones", "Second point"],
    price: 28.99,
    image: "https://example.com/images/sony_mdrzx110nc.jpg",
  },
  {
    id: "17",
    text: "Bose SoundSport Wireless Earbuds",
    description: ["It's a good pair of headphones", "Second point"],
    price: 99.99,
    image: "https://example.com/images/bose_soundsport.jpg",
  },
  {
    id: "18",
    text: "Anker PowerLine+ II Lightning Cable",
    description: ["It's a good pair of headphones", "Second point"],
    price: 16.99,
    image: "https://example.com/images/anker_lightning_cable.jpg",
  },
  {
    id: "19",
    text: "TP-Link AC750 WiFi Extender",
    description: ["It's a good pair of headphones", "Second point"],
    price: 29.99,
    image: "https://example.com/images/tp_link_wifi_extender.jpg",
  },
  {
    id: "20",
    text: "iOttie Easy One Touch 4 Car Mount",
    description: ["It's a good pair of headphones", "Second point"],
    price: 24.99,
    image: "https://example.com/images/iottie_car_mount.jpg",
  },
];

export default products;
