const products = [
  {
    id: "1",
    text: "Vintage Sony Walkman",
    description: ["Classic portable cassette player", "Iconic design"],
    category: "Audio",
    price: 129.99,
    image: "https://example.com/images/vintage_sony_walkman.jpg",
  },
  {
    id: "2",
    text: "Vintage Sennheiser HD414 Headphones",
    description: ["Legendary open-back headphones", "Rich sound quality"],
    category: "Audio",
    price: 149.99,
    image: "https://example.com/images/vintage_sennheiser_hd414.jpg",
  },
  {
    id: "3",
    text: "Vintage IBM Model M Keyboard",
    description: [
      "Mechanical keyboard with buckling springs",
      "Tactile typing experience",
    ],
    category: "Computer Accessories",
    price: 199.99,
    image: "https://example.com/images/vintage_ibm_model_m.jpg",
  },
  {
    id: "4",
    text: "Vintage Polaroid SX-70 Instant Camera",
    description: [
      "Iconic folding instant camera",
      "Produces classic instant photos",
    ],
    category: "Cameras",
    price: 299.99,
    image: "https://example.com/images/vintage_polaroid_sx70.jpg",
  },
  {
    id: "5",
    text: "Vintage Kodak Brownie Hawkeye Camera",
    description: ["Classic box camera design", "Uses 620 film format"],
    category: "Cameras",
    price: 79.99,
    image: "https://example.com/images/vintage_kodak_brownie.jpg",
  },
  {
    id: "6",
    text: "Vintage Grundig Tube Radio",
    description: ["Beautiful wooden cabinet design", "Warm tube sound"],
    category: "Audio",
    price: 299.99,
    image: "https://example.com/images/vintage_grundig_radio.jpg",
  },
  {
    id: "7",
    text: "Vintage Braun T3 Pocket Calculator",
    description: [
      "Slim and stylish pocket calculator",
      "Classic design by Dieter Rams",
    ],
    category: "Calculators",
    price: 59.99,
    image: "https://example.com/images/vintage_braun_calculator.jpg",
  },
  {
    id: "8",
    text: "Vintage Smith-Corona Typewriter",
    description: ["Classic manual typewriter", "Timeless typing experience"],
    category: "Office Equipment",
    price: 199.99,
    image: "https://example.com/images/vintage_smithcorona_typewriter.jpg",
  },
  {
    id: "9",
    text: "Vintage Leica M3 Camera",
    description: ["Legendary rangefinder camera", "Exceptional build quality"],
    category: "Cameras",
    price: 1999.99,
    image: "https://example.com/images/vintage_leica_m3.jpg",
  },
  {
    id: "10",
    text: "Vintage Panasonic RX-5600 Boombox",
    description: [
      "Powerful portable cassette player",
      "Retractable handle and detachable speakers",
    ],
    category: "Audio",
    price: 499.99,
    image: "https://example.com/images/vintage_panasonic_rx5600.jpg",
  },
  {
    id: "11",
    text: "Vintage Zenith Trans-Oceanic Radio",
    description: ["Classic shortwave radio", "Built-in antenna and wood case"],
    category: "Audio",
    price: 399.99,
    image: "https://example.com/images/vintage_zenith_radio.jpg",
  },
  {
    id: "12",
    text: "Vintage Olivetti Valentine Typewriter",
    description: [
      "Italian-designed portable typewriter",
      "Distinctive red color and compact design",
    ],
    category: "Office Equipment",
    price: 499.99,
    image: "https://example.com/images/vintage_olivetti_typewriter.jpg",
  },
  {
    id: "13",
    text: "Vintage Polaroid Land Camera Model 100",
    description: [
      "Instant camera with folding bellows design",
      "Uses peel-apart instant film",
    ],
    category: "Cameras",
    price: 249.99,
    image: "https://example.com/images/vintage_polaroid_land_100.jpg",
  },
  {
    id: "14",
    text: "Vintage Revox A77 Reel-to-Reel Tape Recorder",
    description: [
      "High-end reel-to-reel tape recorder",
      "Studio-quality audio playback",
    ],
    category: "Audio",
    price: 999.99,
    image: "https://example.com/images/vintage_revox_a77.jpg",
  },
  {
    id: "15",
    text: "Vintage Marantz 2270 Stereo Receiver",
    description: [
      "Classic silver-faced stereo receiver",
      "Warm and detailed sound reproduction",
    ],
    category: "Audio",
    price: 899.99,
    image: "https://example.com/images/vintage_marantz_2270.jpg",
  },
  {
    id: "16",
    text: "Vintage Nintendo Entertainment System (NES)",
    description: [
      "Iconic 8-bit gaming console",
      "Includes two controllers and Zapper gun",
    ],
    category: "Gaming",
    price: 199.99,
    image: "https://example.com/images/vintage_nes.jpg",
  },
  {
    id: "17",
    text: "Vintage Atari 2600 Console",
    description: [
      "Classic video game console",
      "Includes joystick and paddle controllers",
    ],
    category: "Gaming",
    price: 149.99,
    image: "https://example.com/images/vintage_atari_2600.jpg",
  },
  {
    id: "18",
    text: "Vintage Apple Macintosh Plus Computer",
    description: [
      "Iconic all-in-one desktop computer",
      "Built-in 9-inch monochrome display",
    ],
    category: "Computers",
    price: 999.99,
    image: "https://example.com/images/vintage_macintosh_plus.jpg",
  },
  {
    id: "19",
    text: "Vintage Commodore 64 Computer",
    description: [
      "Legendary home computer",
      "Popular for gaming and programming",
    ],
    category: "Computers",
    price: 299.99,
    image: "https://example.com/images/vintage_commodore_64.jpg",
  },
  {
    id: "20",
    text: "Vintage Nokia 3310 Cell Phone",
    description: ["Indestructible mobile phone", "Long-lasting battery life"],
    category: "Phones",
    price: 79.99,
    image: "https://example.com/images/vintage_nokia_3310.jpg",
  },
  {
    id: "21",
    text: "Vintage Sony Trinitron Color TV",
    description: ["Iconic CRT television", "Superb color reproduction"],
    category: "Electronics",
    price: 399.99,
    image: "https://example.com/images/vintage_sony_trinitron_tv.jpg",
  },
  {
    id: "22",
    text: "Vintage Bang & Olufsen Beogram Turntable",
    description: ["High-end belt-driven turntable", "Sleek aluminum design"],
    category: "Audio",
    price: 599.99,
    image: "https://example.com/images/vintage_bang_olufsen_turntable.jpg",
  },
  {
    id: "23",
    text: "Vintage Schwinn Bicycle",
    description: ["Iconic American bicycle", "Durable and stylish"],
    category: "Outdoor Recreation",
    price: 499.99,
    image: "https://example.com/images/vintage_schwinn_bicycle.jpg",
  },
  {
    id: "24",
    text: "Vintage Leica M2 Camera",
    description: [
      "Classic rangefinder camera",
      "Timeless design and exceptional optics",
    ],
    category: "Cameras",
    price: 2999.99,
    image: "https://example.com/images/vintage_leica_m2.jpg",
  },
  {
    id: "25",
    text: "Vintage Gibson Les Paul Guitar",
    description: [
      "Iconic electric guitar",
      "Rich tone and superb craftsmanship",
    ],
    category: "Musical Instruments",
    price: 3999.99,
    image: "https://example.com/images/vintage_gibson_les_paul.jpg",
  },
  {
    id: "26",
    text: "Vintage Atari 2600 Video Game Collection",
    description: [
      "Collection of classic Atari 2600 games",
      "Includes iconic titles like Space Invaders and Pac-Man",
    ],
    category: "Gaming",
    price: 499.99,
    image: "https://example.com/images/vintage_atari_2600_games.jpg",
  },
  {
    id: "27",
    text: "Vintage Seiko Pogue Chronograph Watch",
    description: [
      "Legendary Seiko chronograph",
      "Distinctive yellow dial and 70s styling",
    ],
    category: "Watches",
    price: 1499.99,
    image: "https://example.com/images/vintage_seiko_pogue.jpg",
  },
  {
    id: "28",
    text: "Vintage Polaroid SX-70 Land Camera",
    description: [
      "Instant camera with folding design",
      "Produces classic Polaroid instant photos",
    ],
    category: "Cameras",
    price: 499.99,
    image: "https://example.com/images/vintage_polaroid_sx70_land_camera.jpg",
  },
  {
    id: "29",
    text: "Vintage Polaroid Land Camera Model 1000",
    description: ["Classic instant camera", "Simple point-and-shoot operation"],
    category: "Cameras",
    price: 199.99,
    image: "https://example.com/images/vintage_polaroid_land_1000.jpg",
  },
  {
    id: "30",
    text: "Vintage Singer Featherweight Sewing Machine",
    description: [
      "Iconic portable sewing machine",
      "Reliable and precise stitching",
    ],
    category: "Crafts",
    price: 299.99,
    image: "https://example.com/images/vintage_singer_featherweight.jpg",
  },
  {
    id: "31",
    text: "Vintage Remington Rand Typewriter",
    description: [
      "Classic manual typewriter",
      "Sturdy construction for lasting durability",
    ],
    category: "Office Equipment",
    price: 149.99,
    image: "https://example.com/images/vintage_remington_typewriter.jpg",
  },
  {
    id: "32",
    text: "Vintage Hamilton Beach Milkshake Mixer",
    description: [
      "Iconic milkshake mixer",
      "Perfect for retro soda fountain vibes",
    ],
    category: "Kitchen Appliances",
    price: 79.99,
    image: "https://example.com/images/vintage_hamilton_beach_mixer.jpg",
  },
  {
    id: "33",
    text: "Vintage Smith Corona Portable Typewriter",
    description: [
      "Compact and lightweight typewriter",
      "Ideal for on-the-go writing",
    ],
    category: "Office Equipment",
    price: 129.99,
    image: "https://example.com/images/vintage_smithcorona_typewriter.jpg",
  },
  {
    id: "34",
    text: "Vintage Gillette Safety Razor",
    description: [
      "Classic safety razor",
      "Provides a smooth and comfortable shave",
    ],
    category: "Grooming",
    price: 39.99,
    image: "https://example.com/images/vintage_gillette_razor.jpg",
  },
  {
    id: "35",
    text: "Vintage Zenith Trans-Oceanic Shortwave Radio",
    description: [
      "Portable shortwave radio",
      "Explore the world of long-distance broadcasting",
    ],
    category: "Electronics",
    price: 349.99,
    image: "https://example.com/images/vintage_zenith_transoceanic_radio.jpg",
  },
  {
    id: "36",
    text: "Vintage Singer Sewing Machine",
    description: [
      "Classic treadle sewing machine",
      "Beautiful craftsmanship and functionality",
    ],
    category: "Crafts",
    price: 499.99,
    image: "https://example.com/images/vintage_singer_sewing_machine.jpg",
  },
  {
    id: "37",
    text: "Vintage Kodak Brownie Camera",
    description: [
      "Iconic box camera",
      "Captures timeless moments with simplicity",
    ],
    category: "Cameras",
    price: 59.99,
    image: "https://example.com/images/vintage_kodak_brownie_camera.jpg",
  },
  {
    id: "38",
    text: "Vintage Pyrex Mixing Bowls",
    description: [
      "Colorful nesting mixing bowls",
      "Adds retro flair to any kitchen",
    ],
    category: "Kitchenware",
    price: 49.99,
    image: "https://example.com/images/vintage_pyrex_bowls.jpg",
  },
];

export default products;
